### ISSUE TITLE
Request for code

### ISSUE THREAD

**Issue by IOwenI** [omron-sinicx/ncf2#1]
Dear author, I am very interested in your work on "Counterfactual Fairness Filter for Fair-Delay Multi-Robot Navigation". I would appreciate it if you could share your project code.

**Comment by HikaruAsano** [comment]
I appreciate your interest in our project.
We are preparing to release the source code and expect to have the code available by 31 August. We apologize for the delay in releasing the code.

**Comment by IOwenI** [comment]
Appreciate a lot!
